version: "3.8"

services:
  backend:
    build: ./app/backend
    container_name: autoscaleops-backend
    ports:
      - "5000:5000"

  frontend:
    build: ./app/frontend
    container_name: autoscaleops-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
